-- ============================================
-- Safe ALTER TABLE statements for clinic DB
-- Fixes: Field 'id' doesn't have a default value
-- ============================================
-- Run this in phpMyAdmin or MySQL CLI on your live server
-- This script fixes ALL tables with 'id' columns missing AUTO_INCREMENT

-- Core system tables (fixed first)
ALTER TABLE logs MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE store_stock MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE pharmacy_stock MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE sendsignal MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;

-- Add campus_id column to sendsignal if it doesn't exist (for location-based filtering)
ALTER TABLE sendsignal ADD COLUMN campus_id INT NULL DEFAULT NULL AFTER id;

-- Patient & enrollment tables
ALTER TABLE individual MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE company MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE family MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE antenatal MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;

-- Individual record tables
ALTER TABLE company_individual MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE family_individual MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE hmocompany_individual MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE staff MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE student MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;

-- Optional gender columns for patient tables (add if they don't exist)
ALTER TABLE individual
  ADD COLUMN gender VARCHAR(10) NULL DEFAULT NULL AFTER age;

ALTER TABLE student
  ADD COLUMN gender VARCHAR(10) NULL DEFAULT NULL AFTER age;

ALTER TABLE staff
  ADD COLUMN gender VARCHAR(10) NULL DEFAULT NULL AFTER age;

ALTER TABLE family_individual
  ADD COLUMN gender VARCHAR(10) NULL DEFAULT NULL AFTER age;

ALTER TABLE antenatal
  ADD COLUMN gender VARCHAR(10) NULL DEFAULT NULL AFTER age;

-- HMO tables
ALTER TABLE HMO MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE hmocompany MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;

-- Clinical & diagnostic tables
ALTER TABLE patient_lab MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE patient_scan MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE drugchart MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE injectionchart MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;

-- Inventory & setup tables
ALTER TABLE drug MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE card MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE diagnosis MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE procedures MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE room MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE Lab MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE scan MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE lab_location_stock MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;

-- User/Staff tables
ALTER TABLE his_docs MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT PRIMARY KEY;

-- Verify: Run these SELECTs to confirm the fixes
SELECT TABLE_NAME, COLUMN_NAME, EXTRA FROM INFORMATION_SCHEMA.COLUMNS 
  WHERE TABLE_SCHEMA = DATABASE() 
  AND COLUMN_NAME = 'id'
  AND EXTRA NOT LIKE '%auto_increment%'
  ORDER BY TABLE_NAME;
